## O que são ndarray?
São vetores ou matrizes de n-dimensões

In [ ]:
np.random()
np.ones()
np.zeros()
np.all()


In [1]:
import numpy as np

In [2]:
vec_1D = [1,2,3,4,5]

vec_2D = [[1,2,3,4,5],
          [1,2,3,4,5]]

vec_3D = [[1,2,3,4,5],
          [5,4,3,2,1],
          [9,9,9,9,9]]


In [3]:
array_1d = np.array(vec_1D)
array_2d = np.array(vec_2D)
array_3d = np.array(vec_3D)
display(array_3d.shape,array_3d)

(3, 5)

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [9, 9, 9, 9, 9]])

## Indexação de Arrays
Permite selecionar valores de posições especificas de um vetor.

In [4]:
array_3d[2,3]

9

In [5]:
array_3d[0:3,1:3]

array([[2, 3],
       [4, 3],
       [9, 9]])

In [6]:
array_3d[0:3,0]

array([1, 5, 9])

## Funções unitárias

##### **Valor absoluto**: Calcula o valor absoluto de números inteiros, de ponto flutuante e complexos para todos os elementos.


In [7]:
np.abs(-5)

5

##### **Raiz Quadrada**: Calcula a raiz quadrada de cada elemento do array.

In [8]:
np.sqrt(9)

3.0

##### **Exponencial**: Cálculo exponencial de cada elemento do array.


In [9]:
np.exp(2)

7.38905609893065

##### **Logaritimo**: Calcule o logaritmo natural de todos os elementos.


In [10]:
np.log(100)

4.605170185988092

##### Função para encontrar **valores nulos**

In [11]:
np.isnan(array_1d)

array([False, False, False, False, False])

##### **Funções trigonométricas**: Trigonométricas regulares e hiperbólicas.

In [12]:
np.cos(5)

0.28366218546322625

In [13]:
np.sin(34)

0.5290826861200238

## Funções Binárias

##### **Soma** dois arrays

In [14]:
np.add(array_1d,array_1d)

array([ 2,  4,  6,  8, 10])

##### **Subtrai** dois arrays

In [15]:
np.subtract(array_1d,array_1d)

array([0, 0, 0, 0, 0])

##### **Multiplica** dois arrays

In [17]:
np.multiply(array_1d,array_1d)

array([ 1,  4,  9, 16, 25])

##### **Divide** dois arrays

In [18]:
np.divide(array_1d,array_1d)

array([1., 1., 1., 1., 1.])

##### **Compara** dois arrays: Uma comparação para todos os elementos resultando em um array booleano (equivalente aos operadores relacionais >, >=, <, <=, ==, !=)


In [19]:
np.equal(array_1d,array_1d)

array([ True,  True,  True,  True,  True])

## Funções estatisticas e de algebra linear

##### **Soma** todos os elementos do vetor

In [22]:
display(np.sum(array_1d),array_1d)

15

array([1, 2, 3, 4, 5])

##### Calcula a **media** dos elementos do vetor

In [23]:
display(np.mean(array_1d),array_1d)

3.0

array([1, 2, 3, 4, 5])

In [25]:
array_1d.mean()

3.0

##### Calcula o **desvio padrão** do array

In [26]:
array_1d.std()

1.4142135623730951

##### Encontra o menor e maior valor do vetor

In [27]:
array_1d.min()

1

In [28]:
array_1d.max()

5