## O que são ndarray?
São vetores ou matrizes de n-dimensões

In [2]:
import numpy as np

In [3]:
vec_1D = [1,2,3,4,5]

vec_2D = [[1,2,3,4,5],
          [1,2,3,4,5]]

vec_3D = [[1,2,3,4,5],
          [5,4,3,2,1],
          [9,9,9,9,9]]


In [4]:
array_1d = np.array(vec_1D)
array_2d = np.array(vec_2D)
array_3d = np.array(vec_3D)
display(array_3d.shape,array_3d)

(3, 5)

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1],
       [9, 9, 9, 9, 9]])

## Indexação de Arrays
Permite selecionar valores de posições especificas de um vetor.

In [5]:
array_3d[2,3]

9

In [6]:
array_3d[0:3,1:3]

array([[2, 3],
       [4, 3],
       [9, 9]])

In [7]:
array_3d[0:3,0]

array([1, 5, 9])

## Funções unitárias

##### **Valor absoluto**: Calcula o valor absoluto de números inteiros, de ponto flutuante e complexos para todos os elementos.


In [8]:
np.abs(-5)

5

##### **Raiz Quadrada**: Calcula a raiz quadrada de cada elemento do array.

In [9]:
np.sqrt(9)

3.0

##### **Exponencial**: Cálculo exponencial de cada elemento do array.


In [10]:
np.exp(2)

7.38905609893065

##### **Logaritimo**: Calcule o logaritmo natural de todos os elementos.


In [11]:
np.log(100)

4.605170185988092

##### Função para encontrar **valores nulos**

In [12]:
np.isnan(array_1d)

array([False, False, False, False, False])

##### **Funções trigonométricas**: Trigonométricas regulares e hiperbólicas.

In [13]:
np.cos(5)

0.28366218546322625

In [14]:
np.sin(34)

0.5290826861200238

## Funções Binárias

##### **Soma** dois arrays

In [15]:
np.add(array_1d,array_1d)

array([ 2,  4,  6,  8, 10])

##### **Subtrai** dois arrays

In [16]:
np.subtract(array_1d,array_1d)

array([0, 0, 0, 0, 0])

##### **Multiplica** dois arrays

In [17]:
np.multiply(array_1d,array_1d)

array([ 1,  4,  9, 16, 25])

##### **Divide** dois arrays

In [18]:
np.divide(array_1d,array_1d)

array([1., 1., 1., 1., 1.])

##### **Compara** dois arrays: Uma comparação para todos os elementos resultando em um array booleano (equivalente aos operadores relacionais >, >=, <, <=, ==, !=)


In [19]:
np.equal(array_1d,array_1d)

array([ True,  True,  True,  True,  True])

## Funções estatisticas e de algebra linear

##### **Soma** todos os elementos do vetor

In [20]:
display(np.sum(array_1d),array_1d)

15

array([1, 2, 3, 4, 5])

##### Calcula a **media** dos elementos do vetor

In [21]:
display(np.mean(array_1d),array_1d)

3.0

array([1, 2, 3, 4, 5])

In [22]:
array_1d.mean()

3.0

##### Calcula o **desvio padrão** do array

In [23]:
array_1d.std()

1.4142135623730951

##### Encontra o menor e maior valor do vetor

In [24]:
array_1d.min()

1

In [25]:
array_1d.max()

5

## Outras funções e métodos

##### Cria um array com valores "1"

In [27]:
np.ones(5)

array([1., 1., 1., 1., 1.])

##### Cria um array com valores "0"

In [28]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

##### Cria um array com valores "1" ou "0" e com a estrutura de outro array

In [29]:
x = np.arange(6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
np.ones_like(x)

array([[1, 1, 1],
       [1, 1, 1]])

In [31]:
np.zeros_like(x)

array([[0, 0, 0],
       [0, 0, 0]])

##### Cria uma matriz com os valores e estruturas definidas

In [32]:
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

##### Concatena (Une) duas matrizes

In [38]:
x = np.array([[3,4,5],[2,3,4]])
y = np.array([[5,4,3],[2,2,2]])
np.concatenate([x,y])

array([[3, 4, 5],
       [2, 3, 4],
       [5, 4, 3],
       [2, 2, 2]])

##### Divide um array em vários sub-arrays 

In [40]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
np.split(x, 3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

##### Cria uma matriz com elementos repetidos

In [42]:
np.repeat(3,4)

array([3, 3, 3, 3])

In [43]:
np.repeat(2,10)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [45]:
np.repeat([2,5],5)

array([2, 2, 2, 2, 2, 5, 5, 5, 5, 5])

In [47]:
np.repeat([[2,5]],5)

array([2, 2, 2, 2, 2, 5, 5, 5, 5, 5])

##### Insere elementos em uma posição especifica de uma matriz

In [55]:
a = np.array([[1, 1], [2, 2], [3, 3]])
a


array([[1, 1],
       [2, 2],
       [3, 3]])

In [56]:
a = np.insert(a, 1, 5,axis=1)
a

array([[1, 5, 1],
       [2, 5, 2],
       [3, 5, 3]])

##### Acrescenta valores ao final de uma matriz

In [63]:
a = np.array([[1, 1], [2, 2], [3, 3]])
b = np.array([[8, 8], [3, 3], [7, 7]])
np.append(a,b,axis=0)


array([[1, 1],
       [2, 2],
       [3, 3],
       [8, 8],
       [3, 3],
       [7, 7]])

##### Encontra os elementos exclusivos de uma matriz.

In [64]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])